- name: check for /etc/postfix/main.cf
  stat: 
    path: /etc/postfix/main.cf
  register: postfix_config_exists

- name: fail if no postfix config
  fail: msg="/etc/postfix/main.cf not found! Is postfix installed"
  when: not postfix_config_exists.stat.exists

- name: opendkim packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
     - opendkim
     - opendkim-tools

- name: Create /etc/opendkim folder
  file: 
    path: /etc/opendkim
    state: directory
    owner: opendkim
    group: opendkim
    mode: 0755

- name: copy opendkim.conf 
  copy:
    src: opendkim.conf
    dest: /etc/opendkim.conf
    owner: opendkim
    group: opendkim
    mode: 0644
    
- name: modify milter_protocol
  lineinfile:
    path: /etc/postfix/main.cf
    line: milter_protocol = 2
    regex: "^\\s*milter_protocol(.*)"
    
- name: modify milter_default_action
  lineinfile:
    path: /etc/postfix/main.cf
    line: milter_default_action = accept
    regex: "^\\s*milter_default_action(.*)"

- name: Test for line inet:127.0.0.1:8891
  shell: grep -i 'inet:127.0.0.1:8891' /etc/postfix/main.cf 
  ignore_errors: true
  register: test_grep_inet
  changed_when: false

- name: Test for line smtpd_milters
  shell: grep -i "^smtpd_milters| smtpd_milters" /etc/postfix/main.cf 
  ignore_errors: true
  register: test_grep_milter
  changed_when: false

- debug: 
    msg: "{{ test_grep_milter }}"
    tags:
      - debug
      - never

- name: modify smtpd_milters (some milters already defined)
  lineinfile:
    path: /etc/postfix/main.cf
    line: smtpd_milters = inet:127.0.0.1:8891,\1
    regex: "^\\s*smtpd_milters\\s*=\\s*(.*)"
    backrefs: true
  when: (test_grep_inet.stdout == "" and test_grep_milter.stdout != "")

- name: modify smtpd_milters (no milters defined)
  lineinfile:
    path: /etc/postfix/main.cf
    line: smtpd_milters = inet:127.0.0.1:8891
  when: (test_grep_inet.stdout == "" and test_grep_milter.stdout == "")


- name: modify non_smtpd_milters
  lineinfile:
    path: /etc/postfix/main.cf
    line: non_smtpd_milters = $smtpd_milters
    regex: "^\\s*non_smtpd_milters\\s*=\\s*(.*)"
